variables:
  EXE_RELEASE_FOLDER: 'AddFunction\bin\Debug'
  TEST: 'FunctionTest\FunctionTest.csproj'
  DEPLOY_FOLDER: 'C:\Release_bin'
  MSBUILD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe'
  # VSTEST: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
  ARGV: '/p:Configuration=Debug'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  tags:
    - windows
  script:   
    - '$env:MSBUILD'
    - '$env:ARGV'
    - 'nuget restore'
    - '& $env:MSBUILD $env:ARGV'  # build
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - '$env:EXE_RELEASE_FOLDER\AddFunction.exe'  # saving exe to copy to deploy folder
  only:
    - /^(master|dev|release)$/

test_job:
  stage: test
  tags:
    - windows
  script:
    - '$env:TEST'
    # - '$env:VSTEST'
    - 'dotnet test $env:TEST'  # running VSTest
  only:
    - dev

deploy_job:
  stage: deploy
  tags:
    - windows
  script:
    - 'xcopy /y "$env:EXE_RELEASE_FOLDER\AddFunction.exe" "$DEPLOY_FOLDER"'
  only:
    - release